language: python
python:
  - "3.9"
install:
  - pip install pytest nose coveralls
  - pip install -r requirements.txt
  - cp -r core/humanize-locale/ca_ES/ /home/travis/virtualenv/python3.9.1/lib/python3.9/site-packages/humanize/locale/
script:
  - cd core
  - nosetests 
after_success:
  coveralls
